### ISSUE TITLE
roleIdByName test method fails

### ISSUE THREAD

**Issue by FolkertSF** [c4tch/Salesforce-Apex-Test-Framework#10]
c_TestFactory_Test.roleIdByName() passes the Name of a Role to c_TestFactoryMaker.roleIdByName which is supposed to return the Role Id, but returns null, because c_TestFactoryMaker.roleIdByName actually queries the role based on the Developer Name.

I think querying the Role based on developer name makes sense, so the logic is correct. This means we should change the test method to something like this:

```
    @IsTest
    static void roleIdByName() {
        // I can get the ID of a role by DeveloperName
        UserRole r = [select id,DeveloperName from UserRole limit 1];
        System.AssertEquals(r.Id, c_TestFactoryMaker.roleIdByName(r.DeveloperName),'Role ID not retreived for role "'+r.DeveloperName+'"');
    }
```

**Comment by c4tch** [comment]
Thanks, fixed!
