### ISSUE TITLE
Deploy to Salesforce Button is not working

### ISSUE THREAD

**Issue by rajendrasnagar** [c4tch/Salesforce-Apex-Test-Framework#11]
Hey Nine Tails ;),

Great write-up and nice framework. Thanks for Sharing.

DeployToSalesforce button is not working. Check that out.

Regards,
Raj

**Comment by c4tch** [comment]
ok thanks! Will remove the button for now and create an issues to fix later

**Comment by c4tch** [comment]
Reopening, button removed. Add back later. Gitpull working so no rush :) Thanks Raj!

**Comment by c4tch** [comment]
Closing, don't think I'll read add the button will update the deploy info
